Stat svc
CheburatorT1000/java-explore-with-me pull request #1
Opened 2023-03-18 21:30 UTC by CheburatorT1000

2023-03-20 17:31 UTC, alexache requested changes

2023-03-20 17:31 UTC, alexache commented on main/pom.xml
> +            <version>1.18.24</version>
Версии должны быть указаны только в родительском модуле через dependencyManagement

2023-03-20 17:31 UTC, alexache commented on stat/stat-client/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
Можно писать ${project.version}

2023-03-20 17:31 UTC, alexache commented on stat/stat-dto/pom.xml
> +            <version>2.0.2</version>
Такой же комментарий про версии библиотек

2023-03-20 17:31 UTC, alexache commented on stat/stat-dto/src/main/java/ru/practicum/EndpointHitDTO.java
> +    Long id;
Не хватает модификаторов доступа у полей (была задумана аннотация @Value?)

2023-03-20 17:31 UTC, alexache commented on stat/stat-dto/src/main/java/ru/practicum/ViewStatsDTO.java
> +    String app;
И здесь модификаторы доступа

2023-03-20 17:31 UTC, alexache commented on stat/stat-server/pom.xml
> +            <version>1.18.24</version>
Версии библиотек - в родительском модуле

2023-03-20 17:31 UTC, alexache commented on stat/stat-server/src/main/java/ru/practicum/ewm/stat/model/EndpointHit.java
> +    Long id;
Модификаторы доступа

2023-03-20 17:31 UTC, alexache commented on stat/stat-server/src/main/java/ru/practicum/ewm/stat/model/ViewStats.java
> +    String app;
Модификаторы доступа

2023-03-20 17:31 UTC, alexache commented on stat/stat-server/src/main/java/ru/practicum/ewm/stat/service/StatService.java
> +    EndpointHit postHit(EndpointHitDTO endpointHitDTO);
На вход ДТО, на выход модель? Не очень логично с точки зрения интерфейса

2023-03-21 00:35 UTC, CheburatorT1000 commented on main/pom.xml
> +            <version>1.18.24</version>
Разобрался!)

2023-03-21 00:35 UTC, CheburatorT1000 commented on stat/stat-client/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
принял

2023-03-21 00:35 UTC, CheburatorT1000 commented on stat/stat-dto/pom.xml
> +            <version>2.0.2</version>
ок

2023-03-21 00:37 UTC, CheburatorT1000 commented on stat/stat-dto/src/main/java/ru/practicum/EndpointHitDTO.java
> +    Long id;
Модификаторы моя боль) Я не думал об этом, но теперь думаю) в следующих итерациях попробую)

2023-03-21 00:38 UTC, CheburatorT1000 commented on stat/stat-dto/src/main/java/ru/practicum/ViewStatsDTO.java
> +    String app;
fixed

2023-03-21 00:38 UTC, CheburatorT1000 commented on stat/stat-server/pom.xml
> +            <version>1.18.24</version>
fixed

2023-03-21 00:38 UTC, CheburatorT1000 commented on stat/stat-server/src/main/java/ru/practicum/ewm/stat/model/EndpointHit.java
> +    Long id;
fixed

2023-03-21 00:39 UTC, roflcopter90 commented on stat/stat-server/src/main/java/ru/practicum/ewm/stat/service/StatService.java
> +    EndpointHit postHit(EndpointHitDTO endpointHitDTO);
глупо получилось) fixed

2023-03-21 15:43 UTC, alexache approved these changes

2023-03-21 15:47 UTC, merged