Main svc
CheburatorT1000/java-explore-with-me pull request #2
Opened 2023-04-02 15:46 UTC by CheburatorT1000

2023-04-04 15:07 UTC, alexache requested changes

2023-04-04 15:07 UTC, alexache commented on main/pom.xml
> +            <version>${querydsl.version}</version>
Все версии должны быть заданы через dependencyManagement в родительском модуле

2023-04-04 15:07 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/controllers/admin_api/AdminCategoryController.java
> +        return categoryService.save(newCategoryDto);
(опционально) не помешает логгирование в методах контроллера

2023-04-04 15:07 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/entity/model/User.java
> +        return getClass().hashCode();
Лучше тоже полагаться только на id

2023-04-04 15:07 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/services/request/RequestServiceImpl.java
> +    public List<ParticipationRequestDto> privateApiGetUserRequests(Long userId) {
Такие названия в сервисе не очень удачны - они больше говорят о слое представления, чем о собственно том, что делает метод. Например, в следующем методе это еще нагляднее

2023-04-04 15:07 UTC, alexache commented on stat/stat-server/src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:test2
Для чего эти изменения?

2023-04-04 15:07 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/services/event/EventServiceImpl.java
> +        if (eventDto.getEventDate() != null && eventDto.getEventDate().isBefore(LocalDateTime.now())) {
Так же рекомендуется проверять, что событие не менее чем через 2 часа от текущего времени

2023-04-04 15:07 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/services/event/EventServiceImpl.java
> +        log.info("{}", mapOfViews);
Такие логи обычно считаются уровня дебаг, иначе слишком много информации будет в них

2023-04-04 15:07 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/services/event/EventServiceImpl.java
> +        List<Request> requests = requestRepository.findByEventIdInAndStatus(eventsIds, RequestStatus.CONFIRMED);
Будет лучше тоже переделать в мапу, где ключ айди события, а значение количество подтвержденных заявок. Иначе, получается квадратичный алгоритм ниже

2023-04-04 15:07 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/services/event/EventServiceImpl.java
> +        getViewsForEventFullDtos(null, null, Collections.singletonList(eventFullDto));
(опционально) может не помешать добавить отдельный методы не для списков, логика в них заметно проще

2023-04-04 23:56 UTC, CheburatorT1000 commented on stat/stat-server/src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:test2
Это у меня "охота на ведьм была")

2023-04-05 02:28 UTC, CheburatorT1000 commented on main/pom.xml
> +            <version>${querydsl.version}</version>
fixed

2023-04-05 02:29 UTC, CheburatorT1000 commented on main/src/main/java/ru/practicum/ewm/controllers/admin_api/AdminCategoryController.java
> +        return categoryService.save(newCategoryDto);
added

2023-04-05 02:29 UTC, CheburatorT1000 commented on main/src/main/java/ru/practicum/ewm/entity/model/User.java
> +        return getClass().hashCode();
fixed

2023-04-05 02:29 UTC, CheburatorT1000 commented on main/src/main/java/ru/practicum/ewm/services/request/RequestServiceImpl.java
> +    public List<ParticipationRequestDto> privateApiGetUserRequests(Long userId) {
fixed

2023-04-05 02:29 UTC, CheburatorT1000 commented on stat/stat-server/src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:test2
Это у меня "охота на ведьм была")

2023-04-05 02:29 UTC, CheburatorT1000 commented on main/src/main/java/ru/practicum/ewm/services/event/EventServiceImpl.java
> +        if (eventDto.getEventDate() != null && eventDto.getEventDate().isBefore(LocalDateTime.now())) {
fixed

2023-04-05 02:29 UTC, CheburatorT1000 commented on main/src/main/java/ru/practicum/ewm/services/event/EventServiceImpl.java
> +        log.info("{}", mapOfViews);
fixed

2023-04-05 02:30 UTC, CheburatorT1000 commented on main/src/main/java/ru/practicum/ewm/services/event/EventServiceImpl.java
> +        List<Request> requests = requestRepository.findByEventIdInAndStatus(eventsIds, RequestStatus.CONFIRMED);
fixed

2023-04-05 02:30 UTC, CheburatorT1000 commented on main/src/main/java/ru/practicum/ewm/services/event/EventServiceImpl.java
> +        getViewsForEventFullDtos(null, null, Collections.singletonList(eventFullDto));
added

2023-04-05 18:33 UTC, alexache approved these changes

2023-04-05 18:49 UTC, merged