feature: subscriptions
CheburatorT1000/java-explore-with-me pull request #3
Opened 2023-04-07 08:52 UTC by CheburatorT1000

2023-04-07 23:29 UTC, alexache requested changes

2023-04-07 23:29 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/services/event/EventServiceImpl.java
> +        List<Event> events = eventRepository.findByInitiatorIdInAndStateAndEventDateIsAfter(
Мне кажется, что запрос список пользователей, на которых данный пользователь подписан, и поиск событий можно слить в один запрос. Выглядит вполне себе join на вид

2023-04-07 23:29 UTC, alexache commented on postman/feature.json
> +}
Можно добавить еще немного негативных тест кейсов - подписка на несуществующего юзера, подписка на пользователя, у которого есть события в прошлом

2023-04-09 09:30 UTC, CheburatorT1000 commented on main/src/main/java/ru/practicum/ewm/services/event/EventServiceImpl.java
> +        List<Event> events = eventRepository.findByInitiatorIdInAndStateAndEventDateIsAfter(
поправил

2023-04-09 09:33 UTC, CheburatorT1000 commented on postman/feature.json
> +}
добавил еще 2 т.к. по логике основного сервиса я не могу добавить события в прошлом

2023-04-10 13:48 UTC, alexache approved these changes

2023-04-11 20:20 UTC, merged